-- 1. Find the total number of customers who have placed orders. What is the distribution of the customers across states?
SELECT COUNT(*) AS num_of_customers
FROM customer_t;

SELECT COUNT(*) AS num_of_customers, state
FROM customer_t
GROUP BY state
ORDER BY num_of_customers DESC;

-- 2. Which are the top 5 vehicle makers preferred by the customers?
SELECT COUNT(*) AS num_of_orders, vehicle_maker
FROM order_t o
JOIN product_t p USING (product_id)
GROUP BY vehicle_maker
ORDER BY num_of_orders DESC;

-- 3. Which is the most preferred vehicle maker in each state?
SELECT state, vehicle_maker, Vehicles_Ordered
FROM (
SELECT  c.state, p.vehicle_maker, 
        COUNT(o.order_id) AS Vehicles_Ordered,
        RANK()OVER(PARTITION BY state ORDER BY COUNT(o.order_id) DESC) AS rnk
    FROM customer_t c 
    JOIN order_t o ON o.customer_id = c.customer_id
    JOIN product_t p ON p.product_id = o.product_id
    GROUP BY state, vehicle_maker
    ORDER BY state, rnk) as innertable
    WHERE rnk = 1;

-- 4. Find the overall average rating given by the customers. What is the average rating in each quarter?
SELECT AVG(RatingNumber) AS avg_rating
FROM(
SELECT
        CASE 
        WHEN customer_feedback = "Very Bad" THEN 1
        WHEN customer_feedback = "Bad" THEN 2
        WHEN customer_feedback = "Okay" THEN 3
        WHEN customer_feedback = "Good" THEN 4
        WHEN customer_feedback = "Very Good" THEN 5
        END AS RatingNumber
    FROM order_t) as feedbacktable;
    
    -- average by quarter
    SELECT quarter_number, AVG(RatingNumber)
FROM 
(
SELECT
        CASE 
        WHEN customer_feedback = "Very Bad" THEN 1
        WHEN customer_feedback = "Bad" THEN 2
        WHEN customer_feedback = "Okay" THEN 3
        WHEN customer_feedback = "Good" THEN 4
        WHEN customer_feedback = "Very Good" THEN 5
        END AS RatingNumber, quarter_number
    FROM order_t) as ratingstable
    GROUP BY quarter_number
    ORDER BY quarter_number;
    
-- 5. Find the percentage distribution of feedback from the customers. Are customers getting more dissatisfied over time?
SELECT customer_feedback, COUNT(customer_feedback) as RatingCount,
 COUNT(customer_feedback) * 100/(SELECT COUNT(customer_feedback) FROM order_t) AS Percentage_of_Ratings
FROM order_t
GROUP BY customer_feedback
ORDER BY customer_feedback ASC;

-- 6. What is the trend of the number of orders by quarter?
SELECT COUNT(*) AS order_count, quarter_number 
FROM order_t
 GROUP BY 2 
ORDER BY 2;  

-- 7. Calculate the net revenue generated by the company. What is the quarter-over-quarter % change in net revenue?
	-- Total Revenue
SELECT
    ROUND(SUM(quantity * vehicle_price *(1 - discount)), 2) AS Total_Revenue
FROM order_t;

	-- Percent Change Q over Q
SELECT quarter_number, Total_Revenue,
    LAG(Total_Revenue)OVER(ORDER BY quarter_number) AS Previous_Rev,
    ROUND(((Total_Revenue - LAG(Total_Revenue)OVER(ORDER BY quarter_number))/LAG(Total_Revenue)OVER(ORDER BY quarter_number))*100, 2)
    AS Percentage_change
FROM
(
 SELECT
    quarter_number, ROUND(SUM(quantity * vehicle_price *(1 - discount)), 2) AS Total_Revenue
FROM order_t
GROUP BY quarter_number) as innertable
ORDER BY quarter_number;

-- 8. What is the trend of net revenue and orders by quarters?
SELECT
quarter_number, COUNT(DISTINCT order_id) AS orders, ROUND(SUM(quantity * vehicle_price *(1 - discount)), 2) AS Total_Revenue
FROM order_t
GROUP BY quarter_number;

-- 9. What is the average discount offered for different types of credit cards?
SELECT credit_card_type, ROUND(AVG(discount), 2) AS avg_discount
FROM customer_t
JOIN order_t o USING(customer_id)
GROUP BY credit_card_type
ORDER BY avg_discount DESC;

-- 10. What is the average time taken to ship the placed orders for each quarter?
SELECT quarter_number, ROUND(AVG(Days_of_Shipment), 2) avg_shippingtime_days
FROM(
SELECT order_id, quarter_number, order_date, ship_date,
julianday(ship_date) - julianday(order_date) AS Days_of_Shipment
FROM order_t
GROUP BY order_id) as innertable
GROUP BY quarter_number;









    
    





--


